-- Tier-0 profession trainer template for First Aid (TrainerId 9500914).
-- Skill line 129, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 83, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500914;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500914, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 83;

DELETE FROM `trainer_locale` WHERE `Id` = 9500914;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500914, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 83;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500914;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500914, 3279, 100, 0, 0, 0, 0, 0, 0, 0),
(9500914, 3276, 100, 129, 40, 0, 0, 0, 0, 0),
(9500914, 3280, 500, 129, 50, 3273, 0, 0, 0, 0),
(9500914, 3277, 250, 129, 80, 0, 0, 0, 0, 0),
(9500914, 7934, 250, 129, 80, 0, 0, 0, 0, 0),
(9500914, 3278, 1000, 129, 115, 0, 0, 0, 0, 0),
(9500914, 54254, 1000, 129, 125, 3274, 0, 0, 0, 0),
(9500914, 7928, 5000, 129, 150, 0, 0, 0, 0, 0),
(9500914, 7929, 5000, 129, 180, 0, 0, 0, 0, 0),
(9500914, 10847, 25000, 129, 200, 7924, 0, 0, 35, 0),
(9500914, 10840, 10000, 129, 210, 0, 0, 0, 0, 0),
(9500914, 10841, 10000, 129, 240, 0, 0, 0, 0, 0),
(9500914, 18629, 20000, 129, 260, 0, 0, 0, 0, 0),
(9500914, 54255, 20000, 129, 275, 10846, 0, 0, 0, 0),
(9500914, 18630, 20000, 129, 290, 0, 0, 0, 0, 0),
(9500914, 27032, 20000, 129, 300, 0, 0, 0, 0, 0);
