-- Tier-0 profession trainer template for Cooking (TrainerId 9500913).
-- Skill line 185, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 77, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500913;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500913, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 77;

DELETE FROM `trainer_locale` WHERE `Id` = 9500913;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500913, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 77;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500913;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500913, 2551, 100, 0, 0, 0, 0, 0, 0, 0),
(9500913, 37836, 10, 185, 1, 0, 0, 0, 0, 0),
(9500913, 2539, 50, 185, 10, 0, 0, 0, 0, 0),
(9500913, 2541, 100, 185, 50, 0, 0, 0, 0, 0),
(9500913, 3412, 500, 185, 50, 2550, 0, 0, 0, 0),
(9500913, 6499, 100, 185, 50, 0, 0, 0, 0, 0),
(9500913, 2544, 200, 185, 75, 0, 0, 0, 0, 0),
(9500913, 2546, 150, 185, 80, 0, 0, 0, 0, 0),
(9500913, 6500, 300, 185, 125, 0, 0, 0, 0, 0),
(9500913, 54257, 1000, 185, 125, 3102, 0, 0, 0, 0),
(9500913, 4094, 500, 185, 175, 0, 0, 0, 25, 0),
(9500913, 18261, 25000, 185, 200, 3413, 0, 0, 0, 0),
(9500913, 21175, 4000, 185, 200, 0, 0, 0, 0, 0),
(9500913, 54256, 100000, 185, 275, 18260, 0, 0, 0, 0);
