-- Tier-0 profession trainer template for Skinning (TrainerId 9500910).
-- Skill line 393, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 100, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500910;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500910, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 100;

DELETE FROM `trainer_locale` WHERE `Id` = 9500910;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500910, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 100;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500910;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500910, 8615, 10, 0, 0, 0, 0, 0, 0, 0),
(9500910, 8619, 500, 393, 50, 8613, 0, 0, 0, 0),
(9500910, 8620, 5000, 393, 125, 8617, 0, 0, 10, 0),
(9500910, 10769, 50000, 393, 200, 8618, 0, 0, 25, 0),
(9500910, 32679, 100000, 393, 275, 10768, 0, 0, 40, 0);
