-- Tier-0 profession trainer template for Herbalism (TrainerId 9500905).
-- Skill line 182, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 69, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500905;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500905, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 69;

DELETE FROM `trainer_locale` WHERE `Id` = 9500905;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500905, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 69;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500905;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500905, 2372, 10, 0, 0, 0, 0, 0, 5, 0),
(9500905, 2373, 500, 182, 50, 2366, 0, 0, 10, 0),
(9500905, 3571, 5000, 182, 125, 2368, 0, 0, 10, 0),
(9500905, 11994, 50000, 182, 200, 3570, 0, 0, 25, 0),
(9500905, 28696, 100000, 182, 275, 11993, 0, 0, 50, 0);
