-- Tier-0 profession trainer template for Mining (TrainerId 9500909).
-- Skill line 186, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 80, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500909;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500909, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 80;

DELETE FROM `trainer_locale` WHERE `Id` = 9500909;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500909, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 80;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500909;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500909, 2581, 10, 186, 0, 0, 0, 0, 5, 0),
(9500909, 2582, 500, 186, 50, 2575, 0, 0, 10, 0),
(9500909, 2659, 200, 186, 65, 0, 0, 0, 0, 0),
(9500909, 3304, 50, 186, 65, 0, 0, 0, 0, 0),
(9500909, 2658, 200, 186, 75, 0, 0, 0, 0, 0),
(9500909, 3307, 500, 186, 125, 0, 0, 0, 0, 0),
(9500909, 3568, 5000, 186, 125, 2576, 0, 0, 10, 0),
(9500909, 3308, 2500, 186, 155, 0, 0, 0, 0, 0),
(9500909, 3569, 2500, 186, 165, 0, 0, 0, 0, 0),
(9500909, 10097, 5000, 186, 175, 0, 0, 0, 0, 0),
(9500909, 10249, 50000, 186, 200, 3564, 0, 0, 25, 0),
(9500909, 10098, 10000, 186, 230, 0, 0, 0, 0, 0),
(9500909, 16153, 20000, 186, 230, 0, 0, 0, 0, 0),
(9500909, 70524, 10000, 186, 250, 0, 0, 0, 0, 0),
(9500909, 29355, 100000, 186, 275, 10248, 0, 0, 0, 0),
(9500909, 29356, 40000, 186, 275, 0, 0, 0, 0, 0),
(9500909, 35750, 10000, 186, 300, 0, 0, 0, 0, 0),
(9500909, 35751, 10000, 186, 300, 0, 0, 0, 0, 0);
