-- Tier-0 profession trainer template for Fishing (TrainerId 9500915).
-- Skill line 356, recipes and ranks through skill 300.
-- Greeting copied from stock TrainerId 98, which is left untouched.
-- Generated by tools/generate-profession-trainer-sql.py

DELETE FROM `trainer` WHERE `Id` = 9500915;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
SELECT 9500915, `Type`, `Requirement`, `Greeting`, 0 FROM `trainer` WHERE `Id` = 98;

DELETE FROM `trainer_locale` WHERE `Id` = 9500915;
INSERT INTO `trainer_locale` (`Id`, `locale`, `Greeting_lang`, `VerifiedBuild`)
SELECT 9500915, `locale`, `Greeting_lang`, 0 FROM `trainer_locale` WHERE `Id` = 98;

DELETE FROM `trainer_spell` WHERE `TrainerId` = 9500915;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(9500915, 7733, 100, 0, 0, 0, 0, 0, 5, 0),
(9500915, 7734, 500, 356, 50, 7620, 0, 0, 10, 0),
(9500915, 54083, 10000, 356, 125, 7731, 0, 0, 10, 0),
(9500915, 18249, 25000, 356, 200, 7732, 0, 0, 10, 0),
(9500915, 54084, 100000, 356, 275, 18248, 0, 0, 10, 0);
