-- Uninstall mod-tier0-trainers: run by hand against the world DB after removing the module.
-- Generated by tools/generate-profession-trainer-sql.py

UPDATE `creature_default_trainer` d
JOIN `mod_tier0_trainers_backup` b ON b.`CreatureId` = d.`CreatureId`
SET d.`TrainerId` = b.`TrainerId`
WHERE d.`TrainerId` IN (9500902, 9500903, 9500904, 9500905, 9500906, 9500907, 9500908, 9500909, 9500910, 9500911, 9500912, 9500913, 9500914, 9500915);

DROP TABLE IF EXISTS `mod_tier0_trainers_backup`;
DELETE FROM `trainer_spell` WHERE `TrainerId` IN (9500902, 9500903, 9500904, 9500905, 9500906, 9500907, 9500908, 9500909, 9500910, 9500911, 9500912, 9500913, 9500914, 9500915);
DELETE FROM `trainer_locale` WHERE `Id` IN (9500902, 9500903, 9500904, 9500905, 9500906, 9500907, 9500908, 9500909, 9500910, 9500911, 9500912, 9500913, 9500914, 9500915);
DELETE FROM `trainer` WHERE `Id` IN (9500902, 9500903, 9500904, 9500905, 9500906, 9500907, 9500908, 9500909, 9500910, 9500911, 9500912, 9500913, 9500914, 9500915);
DELETE FROM `updates` WHERE `name` LIKE 'mod_tier0_trainers\_%';
