-- Tier-0 profession trainer template for Cooking (TrainerId 77).
-- Skill line 185, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 77;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(77, 2551, 100, 0, 0, 0, 0, 0, 0, 0),
(77, 37836, 10, 185, 1, 0, 0, 0, 0, 0),
(77, 2539, 50, 185, 10, 0, 0, 0, 0, 0),
(77, 2541, 100, 185, 50, 0, 0, 0, 0, 0),
(77, 3412, 500, 185, 50, 2550, 0, 0, 0, 0),
(77, 6499, 100, 185, 50, 0, 0, 0, 0, 0),
(77, 2544, 200, 185, 75, 0, 0, 0, 0, 0),
(77, 2546, 150, 185, 80, 0, 0, 0, 0, 0),
(77, 6500, 300, 185, 125, 0, 0, 0, 0, 0),
(77, 54257, 1000, 185, 125, 3102, 0, 0, 0, 0),
(77, 4094, 500, 185, 175, 0, 0, 0, 25, 0),
(77, 18261, 25000, 185, 200, 3413, 0, 0, 0, 0),
(77, 21175, 4000, 185, 200, 0, 0, 0, 0, 0),
(77, 54256, 100000, 185, 275, 18260, 0, 0, 0, 0);
