-- Tier-0 profession trainer template for Mining (TrainerId 80).
-- Skill line 186, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 80;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(80, 2581, 10, 186, 0, 0, 0, 0, 5, 0),
(80, 2582, 500, 186, 50, 2575, 0, 0, 10, 0),
(80, 2659, 200, 186, 65, 0, 0, 0, 0, 0),
(80, 3304, 50, 186, 65, 0, 0, 0, 0, 0),
(80, 2658, 200, 186, 75, 0, 0, 0, 0, 0),
(80, 3307, 500, 186, 125, 0, 0, 0, 0, 0),
(80, 3568, 5000, 186, 125, 2576, 0, 0, 10, 0),
(80, 3308, 2500, 186, 155, 0, 0, 0, 0, 0),
(80, 3569, 2500, 186, 165, 0, 0, 0, 0, 0),
(80, 10097, 5000, 186, 175, 0, 0, 0, 0, 0),
(80, 10249, 50000, 186, 200, 3564, 0, 0, 25, 0),
(80, 10098, 10000, 186, 230, 0, 0, 0, 0, 0),
(80, 16153, 20000, 186, 230, 0, 0, 0, 0, 0),
(80, 70524, 10000, 186, 250, 0, 0, 0, 0, 0),
(80, 29355, 100000, 186, 275, 10248, 0, 0, 0, 0),
(80, 29356, 40000, 186, 275, 0, 0, 0, 0, 0),
(80, 35750, 10000, 186, 300, 0, 0, 0, 0, 0),
(80, 35751, 10000, 186, 300, 0, 0, 0, 0, 0);
