-- Remap classic profession trainers to canonical TrainerIds.
-- Generated by scripts/generate-profession-trainer-sql.py

-- Blacksmithing: 17 NPCs -> TrainerId 60
UPDATE `creature_default_trainer` SET `TrainerId` = 60 WHERE `CreatureId` IN (514, 1241, 2836, 2998, 3136, 3174, 3355, 3478, 3557, 4258, 4596, 5511, 6299, 15400, 16669, 16724, 17245);

-- Leatherworking: 29 NPCs -> TrainerId 61
UPDATE `creature_default_trainer` SET `TrainerId` = 61 WHERE `CreatureId` IN (1385, 1632, 3007, 3069, 3365, 3549, 3605, 3703, 3967, 4212, 4588, 5127, 5564, 5784, 7866, 7867, 7868, 7869, 7870, 8153, 11097, 11098, 16278, 16688, 16728, 17442, 29507, 29508, 29509);

-- Alchemy: 20 NPCs -> TrainerId 65
UPDATE `creature_default_trainer` SET `TrainerId` = 65 WHERE `CreatureId` IN (1215, 1386, 1470, 2132, 2391, 2837, 3009, 3347, 3603, 3964, 4160, 4611, 4900, 5177, 5499, 7948, 16161, 16642, 16723, 17215);

-- Herbalism: 26 NPCs -> TrainerId 69
UPDATE `creature_default_trainer` SET `TrainerId` = 69 WHERE `CreatureId` IN (812, 908, 1218, 1458, 1473, 2114, 2390, 2856, 3013, 3185, 3404, 3604, 3965, 4204, 4614, 4898, 5137, 5502, 5566, 8146, 12025, 16367, 16644, 16736, 17434, 17983);

-- Tailoring: 16 NPCs -> TrainerId 72
UPDATE `creature_default_trainer` SET `TrainerId` = 72 WHERE `CreatureId` IN (1103, 1346, 2399, 2627, 3004, 3363, 3523, 3704, 4193, 4576, 5153, 11052, 16366, 16640, 16729, 17487);

-- Engineering: 21 NPCs -> TrainerId 84
UPDATE `creature_default_trainer` SET `TrainerId` = 84 WHERE `CreatureId` IN (1676, 1702, 3290, 3494, 5174, 5518, 7406, 7944, 8126, 8736, 8738, 10993, 11017, 11025, 11031, 11037, 16667, 16726, 17222, 29513, 29514);

-- Enchanting: 16 NPCs -> TrainerId 94
UPDATE `creature_default_trainer` SET `TrainerId` = 94 WHERE `CreatureId` IN (1317, 3011, 3345, 3606, 4213, 4616, 5157, 5695, 7949, 11072, 11073, 11074, 16160, 16633, 16725, 19251);

-- Mining: 16 NPCs -> TrainerId 80
UPDATE `creature_default_trainer` SET `TrainerId` = 80 WHERE `CreatureId` IN (1681, 1701, 3001, 3137, 3175, 3357, 3555, 4254, 4598, 5392, 5513, 6297, 8128, 16663, 16752, 17488);

-- Skinning: 19 NPCs -> TrainerId 100
UPDATE `creature_default_trainer` SET `TrainerId` = 100 WHERE `CreatureId` IN (1292, 6287, 6288, 6289, 6290, 6291, 6292, 6295, 6306, 6387, 7087, 7088, 7089, 8144, 12030, 16273, 16692, 16763, 17441);

-- Jewelcrafting: 3 NPCs -> TrainerId 111
UPDATE `creature_default_trainer` SET `TrainerId` = 111 WHERE `CreatureId` IN (15501, 19775, 19778);

-- Inscription: 7 NPCs -> TrainerId 121
UPDATE `creature_default_trainer` SET `TrainerId` = 121 WHERE `CreatureId` IN (30709, 30710, 30711, 30713, 30715, 30716, 30717);

-- Cooking: 20 NPCs -> TrainerId 77
UPDATE `creature_default_trainer` SET `TrainerId` = 77 WHERE `CreatureId` IN (1355, 1699, 3026, 3087, 3399, 4210, 4552, 5159, 5482, 16253, 16277, 17246, 34708, 34710, 34711, 34712, 34713, 34714, 34785, 34786);

-- First Aid: 18 NPCs -> TrainerId 83
UPDATE `creature_default_trainer` SET `TrainerId` = 83 WHERE `CreatureId` IN (2327, 2798, 3181, 3373, 4211, 4591, 5150, 5759, 5939, 5943, 6094, 16272, 16662, 16731, 17214, 17424, 19478, 22477);

-- Fishing: 22 NPCs -> TrainerId 98
UPDATE `creature_default_trainer` SET `TrainerId` = 98 WHERE `CreatureId` IN (1651, 1680, 1683, 1700, 2367, 2834, 3028, 3179, 3332, 3607, 4156, 4573, 5161, 5493, 5690, 5938, 7946, 14740, 16774, 16780, 17101, 18018);
