-- Tier-0 profession trainer template for Herbalism (TrainerId 69).
-- Skill line 182, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 69;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(69, 2372, 10, 0, 0, 0, 0, 0, 5, 0),
(69, 2373, 500, 182, 50, 2366, 0, 0, 10, 0),
(69, 3571, 5000, 182, 125, 2368, 0, 0, 10, 0),
(69, 11994, 50000, 182, 200, 3570, 0, 0, 25, 0),
(69, 28696, 100000, 182, 275, 11993, 0, 0, 50, 0);
