-- Tier-0 profession trainer template for Skinning (TrainerId 100).
-- Skill line 393, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 100;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(100, 8615, 10, 0, 0, 0, 0, 0, 0, 0),
(100, 8619, 500, 393, 50, 8613, 0, 0, 0, 0),
(100, 8620, 5000, 393, 125, 8617, 0, 0, 10, 0),
(100, 10769, 50000, 393, 200, 8618, 0, 0, 25, 0),
(100, 32679, 100000, 393, 275, 10768, 0, 0, 40, 0);
