-- Tier-0 profession trainer template for Fishing (TrainerId 98).
-- Skill line 356, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 98;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(98, 7733, 100, 0, 0, 0, 0, 0, 5, 0),
(98, 7734, 500, 356, 50, 7620, 0, 0, 10, 0),
(98, 54083, 10000, 356, 125, 7731, 0, 0, 10, 0),
(98, 18249, 25000, 356, 200, 7732, 0, 0, 10, 0),
(98, 54084, 100000, 356, 275, 18248, 0, 0, 10, 0);
