-- Tier-0 profession trainer template for First Aid (TrainerId 83).
-- Skill line 129, recipes and ranks through skill 300.
-- Generated by scripts/generate-profession-trainer-sql.py

DELETE FROM `trainer_spell` WHERE `TrainerId` = 83;

INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(83, 3279, 100, 0, 0, 0, 0, 0, 0, 0),
(83, 3276, 100, 129, 40, 0, 0, 0, 0, 0),
(83, 3280, 500, 129, 50, 3273, 0, 0, 0, 0),
(83, 3277, 250, 129, 80, 0, 0, 0, 0, 0),
(83, 7934, 250, 129, 80, 0, 0, 0, 0, 0),
(83, 3278, 1000, 129, 115, 0, 0, 0, 0, 0),
(83, 54254, 1000, 129, 125, 3274, 0, 0, 0, 0),
(83, 7928, 5000, 129, 150, 0, 0, 0, 0, 0),
(83, 7929, 5000, 129, 180, 0, 0, 0, 0, 0),
(83, 10847, 25000, 129, 200, 7924, 0, 0, 35, 0),
(83, 10840, 10000, 129, 210, 0, 0, 0, 0, 0),
(83, 10841, 10000, 129, 240, 0, 0, 0, 0, 0),
(83, 18629, 20000, 129, 260, 0, 0, 0, 0, 0),
(83, 54255, 20000, 129, 275, 10846, 0, 0, 0, 0),
(83, 18630, 20000, 129, 290, 0, 0, 0, 0, 0),
(83, 27032, 20000, 129, 300, 0, 0, 0, 0, 0);
